# Generated by Django 6.0.5 on 2026-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Science', 'Science'), ('History', 'History'), ('Technology', 'Technology'), ('Philosophy', 'Philosophy'), ('Self Development', 'Self Development')], default='Fiction', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
