# Generated by Django 6.0.5 on 2026-05-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_book_id_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='status',
        ),
    ]
